README.md
bot_globals.py
cogs/channels.py
cogs/leaderboards.py
cogs/stats.py
cogs/users.py
main.py
utils/io_handling.py
utils/leaderboards.py

- Make update_stats async. Create io_handling functions for reading and writing to JSON files and wrap with to_thread as they are blocking functions. Revert to previous way of displaying leaderboard but with new order.
- fix send_leaderboard_winners sending every server's leaderboard to all the channels by storing the server's respective channels into the JSONs. This means that dailychannels.txt is now not necessary

Correctly handle blocking function. Store channels in JSON - Remove dailychannels.txt. ReadMe update

---

embeds/general_embeds.py

Updated the help_embed URL to refer to the new _CodeGrind-Team_ GitHub repository.

Update help_embed to link the new GitHub URL

---

bot_globals.py
utils/message_scheduler.py

- The previous implementation was that it would request the daily question for every server which means there are unnecessary requests.
- Remove unnecessary data file creation on startup.

Request and store daily question only once before sending it to all the servers

---

main.py
utils/message_scheduler.py

The issue of multiple instances of the bot being created was due to the fact that the shard id becomes invalidated and so on_ready is rerun. Therefore, to fix this, on_ready had to be replaced with setup_hook as this coroutine only runs once. Setup_hook cannot contain an infinite while loop, therefore send_daily_question_and_update_stats scheduled waiting system had to be replaced with discord.ext.tasks.loop. This did remove the force update functionality, which needs to be implemented back again in the future.

Fix multiple instances of the bot being created

---

cogs/stats.py
embeds/stats_embeds.py

On slower bot host servers, an "interaction has failed" message will be returned due to the fact that the image converter takes a significant time to compute and there was no interaction deferral.

Defer image converter to prevent interaction failed message

---

tests/send_notification.py

Bug where notification sender automation code would send to only one server. This was found to be due to the same instance of a file being used to send to all servers.

Make notification sender send to all servers

---

utils/message_scheduler.py
utils/roles.py

Updating roles takes has been found to take a considerable amount of time to process. Therefore, an investigation will be needed to fix this inefficiency.
For the moment, updating the roles at a less important time of midday rather than midnight (daily_reset) will make the daily_reset notifications to be sent at the appropriate time without a delay.

Update roles at midday UTC rather than midnight UTC

---

cogs/admin.py
cogs/users.py
embeds/users_embeds.py
utils/message_scheduler.py

Due to the discord verification process requiring us to improve our data removal processes, I have implemented the following processes:
- A user can run the /remove permanently_delete=True command which will delete all their data from the database.
- At the beginning of each month, if the users are not connected to the bot in at least one server, all their data is automatically deleted from the database.
- At the beginning of each month, if a server has been deleted or the bot has been kicked from the server, all the server's data is automatically deleted from the database.

Delete user and server data if unneeded

---

utils/questions.py

There were issues with code blocks requiring newlines to be included, but the regex would remove all newlines. So now, only double new lines will be replaced with single new lines after the markdown conversion to remove extra empty lines outside code blocks.

Replace double new lines with a single new line after markdown conversion

---

utils/message_scheduler.py

Due to the refactoring, `get_daily_question` had to be replaced with `daily_question_embed` in message schedule.

Replace get_daily_question with daily_question_embed in message schedule

---

cogs/users.py
utils/questions.py
utils/stats.py

`Shard ID None heartbeat blocked for more than 10 seconds` whilst updating stats. get_problems_solved_and_rank is a blocking function that runs whilst updating stats, therefore, the function has to be run in a different thread.

get_problems_solved_and_rank blocking function is not run in different thread

---

utils/message_scheduler.py

The monthly pruning led to the global leaderboard server with the id of 0 to be deleted.

Prevent execution of data removal processes for global leaderboard server

---

cogs/admin.py
cogs/channels.py
cogs/general.py
cogs/leaderboards.py
cogs/questions.py
cogs/roles.py
cogs/stats.py
cogs/users.py
embeds/general_embeds.py
embeds/questions_embeds.py
embeds/topgg_embeds.py
embeds/users_embeds.py
utils/middleware.py
utils/questions.py
utils/stats.py

Due to the topgg_vote_required decorator that was running code for a duration of time before the interaction was deferred, 'interaction has failed' errors were caused. 
To resolve this, a defer_interaction decorator has been created that defers the message. It also checks if a `display_publicly` parameter is passed to the function which will be taken into consideration, alongside the ephemeral default state provided, when setting the ephemeral state of the response.
This also gave me the opportunity to move the repeated validation of the interaction variable within this new decorator which has decluttered most commands.
Other changes:
- Handle invalid search term for /question search.
- Update some command embed texts and colours.
> Research note: once a response is deferred, the …

Wrap all commands with created defer interaction decorator

---

cogs/users.py
tests/database_utils/link_users_to_server.py
utils/message_scheduler.py
utils/stats.py

Improved reliability through:
- Adding the DBRef directly using AddToSet rather than the shortcut that was previously used. This means that AddToSet won't add if the id already exists in the array. This also improves the speed as the server doesn't need to be manually saved every single time.
- Delete server only after the users are unlinked, so that there aren't any leftover display_informations.
- Set default user's display name for global leaderboard when stats updates.

Replace integer shortcut with DBRef when using AddToSet. and fix remove inactive users logic.

---

middleware/database_middleware.py
utils/stats_utils.py

- Realised that there was no need for filtering out the display informations in user stats, so I removed the code that removes the user's display_information and unlinks them from the corresponding server. The monthly pruning will be responsible for the unlinking.
- Return None if user not found in `update_user_preferences_prompt`

Prevent unlinking of users if user is not a member of guild in cache

---

main.py
utils/dev_utils.py
utils/notifications_utils.py
utils/questions_utils.py

Created `ChannelLogger` class that keeps track of the number of rate limits, and displays them all at once in one message.

fix: Prevent discord channel logger rate limit

---

automations/database_utils/create_dummy_users.py
automations/send_notification.py
bot_globals.py
main.py
utils/dev_utils.py
utils/notifications_utils.py
utils/questions_utils.py

From around 07/03/2024, using LeetCode's API led to 403 status code responses (forbidden access). So, for a potential fix, I copied the headers used in https://github.com/JacobLinCool/LeetCode-Query, because https://github.com/JacobLinCool/LeetCode-Stats-Card works as intended.
- Added new headers.
- Added find_dotenv.
- Added 403 error counting and logging to Discord channel.

Add headers to graphql requests. Add 403 error counting and channel logging.

---

utils/notifications_utils.py

Updating stats takes 5 minutes, so I've decided to now send the daily question before updating the stats, as that's much quicker to do.

Send daily question before updating stats

---

middleware/discord_middleware.py

Allow interactions to be deferred if they're sent from either TextChannels or Threads.

Allow the bot to be used in channel threads

---

ui/constants.py
ui/embeds/problems.py
utils/problems.py

If a premium question is retrieved, now checks if it is a premium question and if it is, sets the content to an empty string in order to prevent a ValueError.

Handle premium questions which don't have content

---

utils/notifications.py
utils/problems.py

Added try except to channel.send when sending the daily question notifications, in the scenario that the bot has missing permissions.

Handle missing required permissions to send daily question to channel

---

utils/notifications.py

Reordered the 'server `last_update` time update' code and the 'continue if global server' code so that the global server is also updated.

Ensure global server's `last_updated` timestamps are updated on schedule

---

utils/notifications.py
utils/roles.py

Even though it is already checked whether the bot has `manage roles` permissions in the guild when updating roles, this still leads sometimes to a discord.errors.Forbidden error being raised when attempting to add roles to a member.
This should be delved a bit deeper to figure out the cause of this inconsistency, however as a temporary fix, we now except a forbidden error if raised to now crash the system.

Catch raised Forbidden error when updating roles

---

bot.py
ui/embeds/leaderboards.py
ui/embeds/problems.py
utils/leaderboards.py

Incorrect record timestamp was retrieved due to the single-line multiple comparison expressions when finding the document.
What has been done:
-  Separated the two timestamp expressions into single expressions.
- Added a missing f-string to a string.
- Added parameter to not display the page count if it's the daily winners leaderboard. As it's unnecessary for that data to be shown on a single page embed.

Separate multiple record timestamp comparisions to retrieve the correct timestamp document

---

cogs/notifications.py
ui/constants.py
ui/embeds/notifications.py
ui/views/notifications.py
utils/notifications.py
utils/problems.py

- Add missing `response_data` NoneType check.
- It seems that `ext.tasks` retry sometimes on some specific exceptions silently, therefore the `reconnect` param has been set to `False`
- Update `/notifications` related embed content to improve clarity.
- Add ephemeral failure message if no notification types were selected when user presses the `save` button in `/notifications'.

fix: Set `reconnect` to `False` to prevent silently handled exceptions in tasks, and add missing `response_data` `NoneType` check

---

bot.py
utils/http_client.py
utils/problems.py
utils/ratings.py

- Handle `aiohttp.ClientError`s in `fetch_data` and `post_data`.
- Create `HttpClient` class to encapsulate all the related logic away from `DiscordBot`
- Move semaphore creation, `RateLimitReachedException` definition, and use of backoff, to `utils/http_client.py`

fix: handle `aiohttp.ClientError`s in `post_data`, and create `HttpClient` class

---

cogs/stats.py
utils/http_client.py

- Handle `asyncio.TimeoutError` which can occur in `discord.commands.ext.tasks` within `fetch_data` and `post_data` when `reconnect` is set to False. (https://stackoverflow.com/a/74110886)
- Check if selected `/stats` user has a preference to prevent preference from being `None`. This was an edge case which occurred if you use /stats on a user that has already connected their account to the bot but not to the server the command was ran from.

Handle `asyncio.TimeoutError` in `fetch_data` and `post_data`

---

utils/problems.py

The follow-up section wasn't always found due to the end whitespace in the search string for it which would only match if the follow-up section wasn't at the end of the question.
- Removed end whitespace in 'follow-up' section search string.

fix: remove end whitespace in 'follow-up' section search string

---

bot.py
ui/embeds/neetcode.py
ui/embeds/problems.py
utils/neetcode.py
utils/problems.py

The NeetCode solutions information is stored in a main.[random_letters_and_numbers].js file in neetcode.io, which can be seen in the sources tab in developer tools. However, the random mix of letters and numbers changes depending on the version of that file, so the solution I found is to fetch `https://neetcode.io`, read the script tag which mentions the most up-to-date version name of the file, then retrieve the file's data using `https://neetcode.io/main.[...].js`. Then the data within the file needs to be parsed using regex, converted to json.
- Create `NeetcodeSolutions` class that stores the solutions and corresponding logic to fetch them from neetcode.io. The solutions are also updated weekly through the task decorator.
- Created a function to fetch the solutions, through the method …

feat: fetch and include video solution link in `/neetcode` embed

---

ui/constants.py
ui/embeds/neetcode.py

Resolves an issue where the Discord spoiler tag would collapse if the code block contained `||` characters.
Check if `response_data` contains `||` characters, replace with `|\u200b|`
- `U+200B` is a zero-width space character. This prevents Discord from interpreting any `||` as the end of the spoiler tag.
The character will be present in the code if copied directly from the spoiler block. This may cause issues if the character is not accounted for before compiling. However, this trade-off is acceptable as users shouldn't be copying code directly without reviewing it first, and having consistent spoiler behaviour across questions is important to improve the user experience.

fix: spoiler tag collapses when code block contains || characters

---

requirements.txt
utils/problems.py

Resolves issue [#153](https://github.com/CodeGrind-Team/CodeGrind-Bot/issues/153).
Improves the random problem retrieval process by excluding premium questions. This is achieved by adding the `isPaidOnly` field to the **fetch_random_question** GraphQL query. If the question is premium-only, we simply fetch another question.
- Modified the GraphQL query in `./utils/problems.py - fetch_random_question` to include the `isPaidOnly` field.
- While `isPaidOnly` is True, we keep calling the **fetch_random_question** function until a non-premium question is found.
This is _most likely_ the best solution. The LeetCode API only supports filtering to display premium questions, with no option to only display non-premium questions.
By including the `isPaidOnly` field within the …

fix: prevent premium questions from being displayed with /problem random

---

ui/embeds/leaderboards.py

Datetimes displayed in the footer of leaderboard embeds were incorrect (1 hour in the past).
The issue was caused due to the unaware datetimes that were converted to timestamps. In order to display the correct timestamp, the datetimes had to be converted to timezone aware datetimes.
Also, the footer question difficulty helper text has been shortened to prevent wrapping on mobile devices.

fix: localize datetimes to display the correct timestamp

---

bot.py
utils/dev.py
utils/neetcode.py
utils/notifications.py
utils/ratings.py
utils/schedules.py

Even though servers, users, and profiles are deleted appropriately when for example users leave servers, or servers get deleted, this important task of deleting no longer needed information can be missed if the bot has an outage or downtime.
Therefore, determining which documents to delete and deleting them on a routinely basis (1 week), would be appropriate to fix this problem.
- Schedule a weekly task that prunes servers that don't have the bot in them, profiles of users that are not in the corresponding guild anymore, and users that don't have any profiles. Note that `fetch_guild` and `fetch_member` are used rather than their `get` counterpart, in order to get accurate and up-to-date data rather than using the cache.
- Move all schedules into a single file.
- Run Neetcode update …

feat: delete servers, users, and profiles when corresponding data is no longer needed

---

bot.py
utils/dev.py
utils/leaderboards.py
utils/stats.py

Due to the global profile of users not being deleted during pruning, this led to `user_to_score[period]` to not contain all the user ids, and as a user_id from a profile with no user was indexes, this led to a KeyError.
1. Verify that user is in `user_to_score[period]` before indexing.
2. Delete global profile if user is bound to get deleted during pruning. Alongside also deleting the user's records.

fix: delete global profile if user gets deleted during pruning and verify user is in `user_to_score[period]`

---

bot.py
utils/http_client.py
utils/stats.py

1. Event raised errors calls the defined `on_error` static method (which is used as the tree's error handler), and thus leads to a parameter mismatch error.
2. Event raised errors aren't logged, and as these are generally critical errors, the bot doesn't currently gracefully close/restart it's system in this situation.
3. User stats updates are run concurrently however this can lead to all threads being blocked.
- Rename `on_error` static method to `tree_on_error`.
- Override `on_error` handler to log (with critical severity) the error, alongside gracefully closing the bot (this will restart it if in production).
- Wrap `update_stats` logic with a semaphore to prevent blocking all threads, and thus should allow users to run other commands whilst the stats routinely update.

fix: handle event raised errors and add semaphore to concurrent user stats updates

---

utils/http_client.py
utils/roles.py
utils/schedules.py

- `response.status` is logged twice, the second time without f-string, potentially causing an exception in certain rare situations.
- Scheduled discord tasks sometimes lead to exceptions, and due to `reconnect` being set to False, once they fail they don't resume. This is intentional functionality, but we want to address this to gracefully handle the exceptions, log them, and resume the task in its next scheduled iteration.
- Remove the remnant print statement in `utils/roles`.
- Remove the repeated `response.status` log.
- Create and wrap all tasks with a task exception handler.

fix(utils/schedules): handle task exceptions and resume on next iteration

---

utils/roles.py

The current role-assigning logic removes all the relevant roles from each verified user, and then assigns the most recent tier to them. However, this is unnecessary and expensive API-wise. 
Now, there are checks in place to prevent unnecessary removal/addition of roles a user already has.

fix(utils/roles): prevent unnecessary role updates

---

cogs/leaderboards.py
ui/constants.py

- Rename the `sort` `/leaderboard` parameter to `sorting` for improved clarity.
- Update the 'codegrind team' `/help` embed to include the new `sorting` parameter.
- Update the `/help` 'admin' commands to latest command id.
- Credit Aqiil for the win-count sorting feature.

docs(leaderboard): Include new `/leaderboard`'s `sorting` parameter in `/help`

---

src/cogs/problems.py
src/utils/problems.py

To solve https://github.com/CodeGrind-Team/CodeGrind-Bot/issues/181, the regex used to replace tags has been replaced with a custom Markdown Converter. Additionally, to prevent the embed's description and field limit from being exceeded, the final content is sliced to fit the limit.
The solution still isn't very robust, but should perform better than before, as seen in testing.

fix(utils/problems): replace regex with HTML parsing, and limit embed size

---

.dockerignore
Dockerfile
docker-compose.yml
src/bot.py
src/main.py
src/observability/monitoring/datadog_client.py

With the completion of #219, a `Dockerfile` and `docker-compose.yml` can be created to setup CodeGrind-Bot and all its dependencies, both on arm64 and amd64.
Added Docker containerisation support for CodeGrind-Bot, enabling deployment in containers with proper dependency management and monitoring integration.
- Implemented Docker containerisation with Dockerfile and docker-compose configuration.
- Integrated Datadog agent for statsd metric collection.

chore(docker): add Docker containerisation support

---

requirements.txt

Reverted the Beanie v2.0.0 upgrade that was causing exceptions:
> discord.app_commands.errors.CommandInvokeError: Command '{command}'
raised an exception: TypeError: object AsyncIOMotorLatentCommandCursor
can't be used in 'await' expression
For the moment, this change will be reverted and the exceptions will be addressed before re-upgrading beanie.

fix(requirements): revert `beanie v2.0.0` upgrade due to exceptions

---

Dockerfile
docker-compose.yml
src/observability/logging/logging_handlers.py

Copy the source code after installing dependencies such that changes in the source code do not invalidate the Docker cache for dependencies.
Additionally, temporarily disable Datadog logging due to issues that will need to be looked into.

chore(dockerfile): move `src` COPY after dependencies and disable datadog logging

---

src/bot.py

Add tag of bot's name to service checks so that they are identifiable from testing bots.
Also, remove unnecessary service check in `on_error`, and convert `on_disconnect` service check to a warning.

chore(bot): add bot name tag to service checks

---

src/bot.py
src/utils/dev.py
src/utils/leaderboards.py
src/utils/notifications.py
src/utils/roles.py
src/utils/schedules.py

Add StatsD metrics for the pruning task and role feature related data.
- Added StatsD metrics for tracking role updates, server counts, and notification events.
- Implemented database pruning metrics to monitor data cleanup operations.
- Updated StatsD tag formatting for consistency and removed confusing `on_disconnect` service check.
- Made sure to remove profiles during pruning when the server no longer exists.

chore(utils): create StatsD metrics for role updates and pruning

---

src/bot.py

Use automatic sharding by changing the base class from `commands.Bot` to `commands.AutoShardedBot`. This change enables the bot to automatically handle sharding as it scales across multiple Discord guilds, which is required by Discord once we reach 2.5k guilds.

chore(bot): use `AutoShardedBot` for automatic sharding

---

src/utils/notifications.py

`discord.bot.roles.servers.count` StatsD gauge was sent even when the roles weren't being updated, therefore, make sure to only send values if it's time to update roles.

fix(utils/notifications): conditionally send `discord.bot.roles.servers.count` gauge

---

src/bot.py
src/utils/schedules.py

- Changed the service check status sent on bot disconnect from `CRITICAL` to `WARNING` in `src/bot.py`, making the alert less severe when the bot randomly disconnects.
- Increased the frequency of the OK service check task in `utils/schedules.py` from every 1 minute to every 30 seconds, allowing for quicker detection of issues.

chore(bot): change `on_disconnect` service check status to WARNING
