main.py

- Provided a default timeout of 10 seconds for all requests
- Selected UTF-8 as the encoding when opening files

Provide timeout for requests, and select encoding when opening files

---

.gitignore
main.py

1. When `add ` command is ran and no leetcode_stats JSON files exists, the existing_data dictionary isn't defined but the code tries to access it. To fix it, I just defined an empty existing_data dictionary.
2. Implemented Pagination for the leaderboard

Leaderboard pagination and fix empty leaderboard error

---

main.py

1. Global difficulty to score values
2. Global rank emojis and concised leaderboard user ranking code
3. Replaced print statements with a logger that stores logs into a file
Note: when using the logger do not use f strings.

Improving code redundancy and clarity

---

.gitignore
.vscode/settings.json
main.py

1. Separate all-time and weekly leaderboard commands and create a general leaderboard function that they utilise.
2. Store the number of questions for each difficulty for each user at the start of the week.
3. Separate update stats function and run on start.

Weekly leaderboard

---

bot_globals.py
cogs/questions.py
utils/questions.py
utils/ratings.py

get_rating_data is a blocking function. Had to wrap it with the to_thread decorator

Fix get_rating_data blocking function

---

cogs/admin.py
cogs/channels.py
cogs/general.py
cogs/leaderboards.py
cogs/questions.py
cogs/stats.py
cogs/users.py
database.py
models/analytics_model.py
utils/message_scheduler.py
utils/middleware.py

- Create analytics MongoDB model
- Stores the current day's command count and distinct users that ran a command
- Stores the data into history

Add analytics

---

cogs/stats.py
embeds/general_embeds.py
embeds/stats_embeds.py

Credit to https://github.com/JacobLinCool/LeetCode-Stats-Card for the generated LeetCode stats cards.

Use html2image to convert LeetCode user stats card svg to png

---

cogs/leaderboards.py
main.py
utils/message_scheduler.py
utils/views.py

- Missing imports
- Incorrect/confusing use of correct interaction send_message and followup, therefore all the leaderboard-related code has been reverted.

Fix deferring errors

---

utils/roles.py

Previously, the program was attempting to directly remove the role from the user without checking if the user has that role which was very time-consuming.

Check if user has the role before attempting to remove it

---

bot_globals.py
tests/send_notification.py
utils/leaderboards.py
utils/message_scheduler.py

- The bot doesn't need all the intents, therefore, the default ones will be used so that the bot can continue to be added to servers.
- Check if the channel exists before sending it a notification.

Use default intents and validate the channel's existence

---

bot_globals.py

Members intents are needed for specific discord functions such as get_member().

Add members intents

---

cogs/leaderboards.py
cogs/questions.py
cogs/users.py
embeds/general_embeds.py
embeds/users_embeds.py
main.py
utils/questions.py

- Defer leaderboard interaction. 
- Update add account instructions. 
- Rename /add command parameter leetcode_username to leetcode_id.

QOL improvements: prevent interaction has failed on leaderboard commands, and make account adding instructions clearer

---

embeds/general_embeds.py

Please review this privacy policy note - will help us better tell users about the privacy we offer.

Add Privacy Policy to /help

---

utils/roles.py
utils/stats.py

Correctly reset users streaks on daily reset. Remove all streak roles and assign the correct new streak role to each user.

Correctly reset streaks and assign appropriate streak role to users

---

utils/message_scheduler.py

Update user stats concurrently using await asyncio.gather(*tasks).

Update user stats concurrently

---

embeds/leaderboards_embeds.py
utils/common_utils.py
utils/leaderboards_utils.py

e.g. from 05/12/2023 to 5th Dec 2023

Format datetime to include day suffix and abbreviated month name

---

database/models/user_model.py
embeds/topgg_embeds.py
embeds/users_embeds.py
middleware/database_middleware.py
middleware/topgg_middleware.py
utils/leaderboards_utils.py

- Access to restricted commands lasts a specific amount of time since voting. 
- Rename `private` display_information field to `visible`.

Time based access to restricted commands since last voted

---

utils/leaderboards_utils.py

Current logic only displayed one of the 3rd place winners in the leaderboard.

Display all third place winners

---

cogs/users_cog.py
requirements.txt
utils/dev_utils.py
utils/notifications_utils.py
utils/questions_utils.py
utils/stats_utils.py

The LeetCode API started to rate limit our requests, therefore, I've implemented exponential backoff to retry the requests if rate limit is reached.

Implement exponential backoff, asynchronous requests, and developer channel logs

---

bot.py
cogs/problems.py
ui/embeds/problems.py
ui/modals/problems.py
utils/notifications.py
utils/problems.py
utils/ratings.py
utils/stats.py
utils/users.py

Centralises the aiohttp client session management within the `DiscordBot` class to ensure proper handling of sessions and prevent potential session-closed exceptions (which occurred when DiscordBot `self` was passed as argument to a function, which led to the session being closed). It encapsulates the session management and provides and interfaces for performing GET and POST requests.
- Added `fetch_data` method to perform GET requests.
- Added `post_data` method to perform POST requests.
- The new methods accept variable positional and keyword arguments for maintaining current usage with limited changes required.
- Ensured proper session closure with the `close` method.
- Graceful closing of client session, bot, and device.

chore: centralised client session management in `DiscordBot` class

---

database/models/__init__.py
database/models/record.py
database/models/user.py
utils/problems.py
utils/stats.py

- Created new data classes for skill tags and languages.
- Edited the query in `fetch_problems_solved_and_rank` to query the required data.
- Added new BaseModels to `user.py` for the new data.
- Added new attributes to Record `record.py` for the new BaseModels.
- Edited `update_stats` to provide the new data into the Record constructor.
- Imported the new BaseModels in `database/models/__init__.py`

feat: store users languages and skills problem count data

---

utils/stats.py

- The win_counts don't seem to update.
- Profiles' `win_count.last_updated` isn't updated.
- Update wins after the user stats update, and therefore setting `previous` to `true` in the `all_users_and_scores` call.
- Set the profile's last_updated time to the time of win_count updating.

fix: update wins after stats update and update `Profile.win_count.last_updated`

---

ui/embeds/problems.py
utils/problems.py

There is a rare situation when retrieved user stats have empty fields that we currently assume always are present, leading to a typeerror.
Handle this TypeError similarly to how we handle ValueError within user stats retrieval.

fix: handle user stats retrieval TypeError when fields are empty

---

.github/CODEOWNERS

The codeowner should be automatically requested for review of PRs, such that they receive prompt notifications.

chore(codeowners): add codeowners of repo for auto review requesting

---

README.md
requirements.txt
src/bot.py
src/main.py
src/observability/logging/__init__.py
src/observability/logging/handlers/__init__.py
src/observability/logging/handlers/console_logger.py
src/observability/logging/handlers/file_logger.py
src/observability/logging/handlers/gcp_logger.py
src/observability/logging/loggers.py
src/observability/logging/logging_handlers.py
src/observability/monitoring/__init__.py
src/observability/monitoring/datadog_client.py
src/utils/channel_logging.py
src/utils/dev.py
src/utils/notifications.py
src/utils/stats.py

Improved observability through metrics, alerts, and uptime checks is necessary for faster downtime response. 
The first step necessary - and the purpose of this PR - is to modularise logging-related functionality and setup, and integrate Datadog initialisation on Bot setup.
1. Refactored logging-related functionality into its own directory.
2. Integrated Datadog initialisation.

chore(monitoring): modularise observability and integrate Datadog initialisation

---

docker-compose.yml
requirements.txt
src/observability/logging/handlers/__init__.py
src/observability/logging/handlers/json_logger.py
src/observability/logging/logging_handlers.py
src/utils/stats.py

Added JSON logging support for Datadog integration by implementing a JSON formatter and restructuring the logging handlers to use different configurations for production and non-production environments.
- Added JSON logging handler.
- Updated Docker Compose configuration to enable Datadog log collection.
- Refactored logging handler selection based on production vs non-production environments.

chore(logging): add JSON logging handler for datadog logging support

---

src/bot.py
src/cogs/problems.py
src/main.py
src/utils/channel_logging.py
src/utils/dev.py
src/utils/http_client.py
src/utils/leaderboards.py
src/utils/neetcode.py
src/utils/notifications.py
src/utils/problems.py
src/utils/ratings.py
src/utils/schedules.py
src/utils/stats.py

This PR improves signal handling for cross-platform compatibility and enhances log message consistency and clarity throughout the codebase.
- Added error handling for signal handlers that are not supported on Windows.
- Standardised log message format to use structured logging with pipe separators.
- Enhanced TopGG client initialisation with HTTP session sharing.

chore(src): handle signal handling non-support and standardise logs
